---

- name: setting docker-hdp
  file: path={{item}} state=directory
  with_items:
    - /opt/docker-hdp
    - /opt/clustertest
    - /opt/clustertest/hdp

- name: clone directory
  git:
    repo: https://github.com/randerzander/docker-hdp.git
    dest: /opt/docker-hdp
    clone: yes

- name: uploading scripts
  copy: 
    src: "{{item}}"
    dest: /opt/clustertest/hdp
    mode: 755
  with_fileglob:
    - "*sh"

- name: uploading jsons
  copy: 
    src: "{{item}}"
    dest: /opt/clustertest/hdp
    mode: 644
  with_fileglob:
    - "*json"
