---

- name: setting clusterdock
  file: path=/opt/clusterdock state=directory

- name: clone directory
  git:
    repo: https://github.com/cloudera/clusterdock.git
    dest: /opt/clusterdock
    clone: yes

- name: clusterdock requirements
  pip:
    requirements: /opt/clusterdock/requirements.txt

- name: setting clusterdock run scripts
  file: path=/opt/clusterdock-scripts state=directory

- name: uploading scripts
  copy: 
    src: "{{item}}"
    dest: /opt/clusterdock-scripts
    mode: 755
  with_fileglob:
    - "*"
