---

- name: setting clusterdock
  file: path={{item}} state=directory
  with_items:
    - /opt/clusterdock
    - /opt/clustertest
    - /opt/clustertest/cdh

- name: clone directory
  git:
    repo: https://github.com/cloudera/clusterdock.git
    dest: /opt/clusterdock
    clone: yes

- name: clusterdock requirements
  pip:
    requirements: /opt/clusterdock/requirements.txt

- name: removing docker-py
  pip: name={{item}} state=absent
  with_items:
    - docker-py
    - docker

- name: install latest docker
  pip: name={{item}} state=latest
  with_items:
    - docker 
#    - docker-py

- name: uploading scripts
  copy: 
    src: "{{item}}"
    dest: /opt/clustertest/cdh
    mode: 755
  with_fileglob:
    - "*"
