---

- name: uninstall packages if exists 
  apt: name={{item}} state=absent
  with_items: 
    - docker
    - docker-engine

- name: Installing docker requirements
  apt: name={{item}} state=present
  with_items:
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - software-properties-common

- name: Adding key for apt repository
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
    state: present

- name: Adding docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present

- name: Install docker container edition
  apt: name=docker-ce state=present

- name: Install latest docker-compose 
  get_url:
    url: https://github.com/docker/compose/releases/download/1.13.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose 
    mode: 755
